version: '3.8'  # 最新のバージョンを使用することを推奨

services:
  backend:
    build: ./backend
    ports:
      - '5050:5050'
    env_file:
      - ./.env
    networks:
      - app-network
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
    # コマンドを追加して起動時にマイグレーションを自動実行することも可能
    # command: sh -c "alembic upgrade head && python -m app.main"

  frontend:
    build: ./study-support-app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./study-support-app:/app
    env_file:
      - ./.env
    restart: always
    command: npm run dev
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5050

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5020:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d demo"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
