version: '3.8'  # 最新のバージョンを使用することを推奨

services:
  backend:
    build: ./backend
    ports:
      - '5050:5050'
    env_file:
      - ./.env
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      # RDSへの接続を確実にするための追加設定
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./study-support-app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./study-support-app:/app
    env_file:
      - ./.env
    restart: always
    command: npm run dev
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5050

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
