"""Set cascade delete on User.chat_messages relationship

Revision ID: 0a9d77746213
Revises: 9760a5649ebe
Create Date: 2025-04-26 15:08:04.901380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9d77746213'
down_revision: Union[str, None] = '9760a5649ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
