"""change status

Revision ID: 0b0fb46e8ec7
Revises: 90051dd3121d
Create Date: 2025-01-02 02:31:31.561613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0fb46e8ec7'
down_revision: Union[str, None] = '90051dd3121d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_evaluations', 'completion_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('checklist_evaluations', 'ai_feedback',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_checklist_evaluations_id', table_name='checklist_evaluations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_checklist_evaluations_id', 'checklist_evaluations', ['id'], unique=False)
    op.alter_column('checklist_evaluations', 'ai_feedback',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('checklist_evaluations', 'completion_status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
