"""Add unpaid value to UserStatus enum

Revision ID: 0bd02b19ec1a
Revises: 0a9d77746213
Create Date: 2025-04-26 15:30:29.997168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# --- 追加 ---
# Enum 型の定義 (models/enums.py と同じ値を定義)
user_status_enum = sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'UNPAID', name='userstatus')
# --- 追加ここまで ---


# revision identifiers, used by Alembic.
revision: str = '0bd02b19ec1a'
down_revision: Union[str, None] = '0a9d77746213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- 追加 ---
    # Enum 型を作成
    user_status_enum.create(op.get_bind(), checkfirst=True)
    # --- 追加ここまで ---
    op.add_column('users', sa.Column('status', user_status_enum, nullable=False, server_default='PENDING'))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, server_default=sa.text('true')))
    op.drop_column('users', 'status')
    # --- 追加 ---
    # Enum 型を削除
    user_status_enum.drop(op.get_bind(), checkfirst=True)
    # --- 追加ここまで ---
    # ### end Alembic commands ###
