"""add_stripe_db_product_table_and_update_subscription_plan

Revision ID: 1127d594eb02
Revises: 22da79414eac
Create Date: 2025-05-07 08:30:59.238446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1127d594eb02'
down_revision: Union[str, None] = '22da79414eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_db_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stripe_product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_db_products_stripe_product_id'), 'stripe_db_products', ['stripe_product_id'], unique=True)
    op.add_column('subscription_plans', sa.Column('stripe_db_product_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_subscription_plans_stripe_db_product_id'), 'subscription_plans', ['stripe_db_product_id'], unique=False)
    op.create_foreign_key(None, 'subscription_plans', 'stripe_db_products', ['stripe_db_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_plans', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plans_stripe_db_product_id'), table_name='subscription_plans')
    op.drop_column('subscription_plans', 'stripe_db_product_id')
    op.drop_index(op.f('ix_stripe_db_products_stripe_product_id'), table_name='stripe_db_products')
    op.drop_table('stripe_db_products')
    # ### end Alembic commands ###
