"""add stripe_db_product_id to subscription_plans

Revision ID: 2ec1940cd924
Revises: 953a53321a83
Create Date: 2025-05-08 06:54:12.547998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec1940cd924'
down_revision: Union[str, None] = '953a53321a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
