"""add_self_analysis_chat_to_personal_statement

Revision ID: 35f0afce7d8d
Revises: 5456ecb2384a
Create Date: 2025-05-21 20:11:49.518870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f0afce7d8d'
down_revision: Union[str, None] = '5456ecb2384a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_statements', sa.Column('self_analysis_chat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'personal_statements', 'chat_sessions', ['self_analysis_chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_statements', type_='foreignkey')
    op.drop_column('personal_statements', 'self_analysis_chat_id')
    # ### end Alembic commands ###
