"""add_title_keyword_personal_statement

Revision ID: 3874a76ae8c8
Revises: 35f0afce7d8d
Create Date: 2025-05-21 21:30:12.470637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3874a76ae8c8'
down_revision: Union[str, None] = '35f0afce7d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_statements', sa.Column('title', sa.String(), nullable=True))
    op.add_column('personal_statements', sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_statements', 'keywords')
    op.drop_column('personal_statements', 'title')
    # ### end Alembic commands ###
