"""change-content

Revision ID: 3bf84bfb1563
Revises: 7da30fa3551c
Create Date: 2025-05-15 11:54:10.571141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf84bfb1563'
down_revision: Union[str, None] = '7da30fa3551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contents', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'created_by_id')
    # ### end Alembic commands ###
