"""add_faq_and_consultation_to_chattype_enum

Revision ID: 7da30fa3551c
Revises: 2ec1940cd924
Create Date: 2025-05-09 07:13:18.521859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da30fa3551c'
down_revision: Union[str, None] = '2ec1940cd924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
