"""add-content-provider

Revision ID: 8aab50e28fbf
Revises: 1d17ec1ccf96
Create Date: 2025-05-15 15:00:54.541643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aab50e28fbf'
down_revision: Union[str, None] = '1d17ec1ccf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('provider_item_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'provider_item_id')
    op.drop_column('contents', 'provider')
    # ### end Alembic commands ###
