"""remove_unique_constraint_from_subscription_plan_name

Revision ID: 953a53321a83
Revises: 1127d594eb02
Create Date: 2025-05-07 11:58:16.757549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953a53321a83'
down_revision: Union[str, None] = '1127d594eb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_plans_name_key', 'subscription_plans', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subscription_plans_name_key', 'subscription_plans', ['name'])
    # ### end Alembic commands ###
