"""Add cascade delete to chat_messages user relationship

Revision ID: 9760a5649ebe
Revises: 8d2bf69bed5f
Create Date: 2025-04-26 15:02:18.169040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9760a5649ebe'
down_revision: Union[str, None] = '8d2bf69bed5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
