"""add_agent_table

Revision ID: dd1a15413b43
Revises: 3874a76ae8c8
Create Date: 2025-05-23 00:37:13.391292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1a15413b43'
down_revision: Union[str, None] = '3874a76ae8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('policy_title', sa.String(), nullable=True),
    sa.Column('policy_content', sa.Text(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_statement_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_agent_id', sa.String(), nullable=False),
    sa.Column('rubric_id', sa.String(), nullable=True),
    sa.Column('score_table', sa.JSON(), nullable=False),
    sa.Column('advice_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personal_statement_id'], ['personal_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_statement_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('personal_statement_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=False),
    sa.Column('edited_by_agent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['personal_statement_id'], ['personal_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profiles', sa.Column('current_grade', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('class_name', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('academic_interests', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('career_goals', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('significant_experiences', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('self_assessment_strengths', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('self_assessment_weaknesses', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_learning_style', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('motivation_statement_prompt_answers', sa.JSON(), nullable=True))
    op.drop_column('user_profiles', 'grade')
    op.drop_column('user_profiles', 'class_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('class_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'motivation_statement_prompt_answers')
    op.drop_column('user_profiles', 'preferred_learning_style')
    op.drop_column('user_profiles', 'self_assessment_weaknesses')
    op.drop_column('user_profiles', 'self_assessment_strengths')
    op.drop_column('user_profiles', 'significant_experiences')
    op.drop_column('user_profiles', 'career_goals')
    op.drop_column('user_profiles', 'academic_interests')
    op.drop_column('user_profiles', 'class_name')
    op.drop_column('user_profiles', 'current_grade')
    op.drop_table('personal_statement_revisions')
    op.drop_table('evaluation_results')
    op.drop_table('admission_policies')
    # ### end Alembic commands ###
