"""add grade and pref

Revision ID: e3aa8f6ff620
Revises: b1f29507ed5e
Create Date: 2025-04-30 21:20:34.540645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3aa8f6ff620'
down_revision: Union[str, None] = 'b1f29507ed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('prefecture', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'prefecture')
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###
