"""FixCupon

Revision ID: ec1ef2c06cf2
Revises: 17c7d9e895ee
Create Date: 2025-05-06 17:02:28.721202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec1ef2c06cf2'
down_revision: Union[str, None] = '17c7d9e895ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add step to delete rows where coupon_id is NULL before adding NOT NULL constraint
    op.execute("DELETE FROM campaign_codes WHERE coupon_id IS NULL")

    op.alter_column('campaign_codes', 'coupon_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('stripe_coupons', sa.Column('valid', sa.Boolean(), nullable=True))
    op.add_column('stripe_coupons', sa.Column('livemode', sa.Boolean(), nullable=True))
    op.add_column('stripe_coupons', sa.Column('stripe_created', sa.Integer(), nullable=True))
    op.alter_column('stripe_coupons', 'redeem_by',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='EXTRACT(EPOCH FROM redeem_by)::integer')
    op.drop_column('stripe_coupons', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_coupons', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('stripe_coupons', 'redeem_by',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('stripe_coupons', 'stripe_created')
    op.drop_column('stripe_coupons', 'livemode')
    op.drop_column('stripe_coupons', 'valid')
    op.alter_column('campaign_codes', 'coupon_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
