name: Run STG DB Migrations

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: >
          Run DB migrations on STG? (Type 'yes' to confirm)
        required: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  run-db-migrations-stg:
    name: Run DB Migrations on STG
    if: github.event.inputs.confirm == 'yes'
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Run DB migrations on ECS
        run: |
          echo "Running DB migrations on STG environment..."
          aws ecs run-task \
            --cluster smartao-api-stg \
            --launch-type FARGATE \
            --task-definition backend-stg \
            --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.STG_SUBNETS }}],securityGroups=[${{ secrets.STG_SECURITY_GROUPS }}],assignPublicIp=DISABLED}" \
            --overrides '{"containerOverrides":[{"name":"backend","command":["alembic","upgrade","head"]}]}' \
            --output json | cat
          echo "DB migration task started. Check ECS console for status." 