name: Build & Push STG Docker Images to ECR

on:
  push:
    branches:
      - stg

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

jobs:
  # AWS 認証 & ECR ログイン
  ecr-login:
    environment: Production
    runs-on: ubuntu-latest
    outputs:
      login: ${{ steps.login-ecr.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  # Backend STG イメージのビルド & プッシュ
  build-push-backend-stg:
    needs: ecr-login
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build STG backend image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/api:stg
          docker build \
            --file backend/Dockerfile.stg \
            --tag  $IMAGE_URI \
            backend

      - name: Push STG backend to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/api:stg

  # Frontend STG イメージのビルド & プッシュ
  build-push-frontend-stg:
    needs: ecr-login
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build STG frontend image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/front:stg
          docker build \
            --file study-support-app/Dockerfile.stg \
            --tag  $IMAGE_URI \
            study-support-app

      - name: Push STG frontend to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/front:stg 