name: Build & Push STG Docker Images to ECR

on:
  push:
    branches:
      - stg
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

jobs:
  # AWS 認証 & ECR ログイン
  ecr-login:
    needs: infra-setup
    environment: Preview
    runs-on: ubuntu-latest
    outputs:
      login: ${{ steps.login-ecr.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  # Backend STG イメージのビルド & プッシュ
  build-push-backend-stg:
    needs: ecr-login
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build STG backend image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/api:stg
          docker build \
            --file backend/Dockerfile.stg \
            --tag  $IMAGE_URI \
            backend

      - name: Push STG backend to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/api:stg

  # Frontend STG イメージのビルド & プッシュ
  build-push-frontend-stg:
    needs: ecr-login
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build STG frontend image
        run: |
          IMAGE_URI=${{ env.ECR_REGISTRY }}/front:stg
          docker build \
            --file study-support-app/Dockerfile.stg \
            --tag  $IMAGE_URI \
            study-support-app

      - name: Push STG frontend to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/front:stg

  # DB migration on ECS
  run-db-migrations:
    needs: build-push-backend-stg
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Run DB migrations on ECS
        run: |
          aws ecs run-task \
            --cluster smartao-api-stg \
            --launch-type FARGATE \
            --task-definition backend-stg \
            --network-configuration "awsvpcConfiguration={subnets=[${{ secrets.STG_SUBNETS }}],securityGroups=[${{ secrets.STG_SECURITY_GROUPS }}],assignPublicIp=DISABLED}" \
            --overrides '{"containerOverrides":[{"name":"backend","command":["alembic","upgrade","head"]}]}'

  deploy-backend-stg:
    needs: run-db-migrations
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Deploy Backend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          cluster: smartao-api-stg
          service: smartao-api-stg-service
          task-definition: ECS/backend-task-def-stg.json
          wait-for-service-stability: true

  deploy-frontend-stg:
    needs: build-push-frontend-stg
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}
      - name: Deploy Frontend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          cluster: smartao-front-stg
          service: smartao-front-stg-service
          task-definition: ECS/frontend-task-def-stg.json
          wait-for-service-stability: true 