name: Build & Push STG Docker Images to ECR

on:
  push:
    branches:
      - stg
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}

jobs:
  # Backend STG イメージのビルド & プッシュ
  build-push-backend-stg:
    environment: Preview
    runs-on: ubuntu-latest
    outputs:
      latest_image_uri: ${{ steps.build-image.outputs.latest_image_uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build STG backend image
        id: build-image
        run: |
          REGISTRY=$(echo "${{ secrets.AWS_ECR_REGISTRY }}" | sed 's:/*$::')
          IMAGE_URI="${REGISTRY}/stg-backend:latest"
          docker build \
            --file backend/Dockerfile.stg \
            --tag  $IMAGE_URI \
            backend
          echo "latest_image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "::set-output name=latest_image_uri::$IMAGE_URI"

      - name: Push STG backend to ECR
        run: |
          REGISTRY=$(echo "${{ secrets.AWS_ECR_REGISTRY }}" | sed 's:/*$::')
          docker push ${REGISTRY}/stg-backend:latest

  # Frontend STG イメージのビルド & プッシュ
  build-push-frontend-stg:
    environment: Preview
    runs-on: ubuntu-latest
    outputs:
      latest_image_uri: ${{ steps.build-image.outputs.latest_image_uri }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build STG frontend image
        id: build-image
        run: |
          REGISTRY=$(echo "${{ secrets.AWS_ECR_REGISTRY }}" | sed 's:/*$::')
          IMAGE_URI="${REGISTRY}/stg-frontend:latest"
          docker build \
            --file study-support-app/Dockerfile.stg \
            --tag  $IMAGE_URI \
            study-support-app
          echo "latest_image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
          echo "::set-output name=latest_image_uri::$IMAGE_URI"

      - name: Push STG frontend to ECR
        run: |
          REGISTRY=$(echo "${{ secrets.AWS_ECR_REGISTRY }}" | sed 's:/*$::')
          docker push ${REGISTRY}/stg-frontend:latest

  deploy-backend-stg:
    needs: build-push-backend-stg
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}
      - name: "Debug: Confirm backend image URI"
        run: echo "Backend IMAGE URI: ${{ needs.build-push-backend-stg.outputs.latest_image_uri }}"
      - name: Render ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: backend-stg
          container-name: backend
          image: ${{ needs.build-push-backend-stg.outputs.latest_image_uri }}
      - name: Deploy Backend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: stg-api
          service: stg-api-service
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          wait-for-service-stability: true
      - name: "Debug: Built image URI"
        run: |
          echo "latest_image_uri: ${{ needs.build-push-backend-stg.outputs.latest_image_uri }}"

  deploy-frontend-stg:
    needs: build-push-frontend-stg
    environment: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}
      - name: "Debug: Confirm frontend image URI"
        run: echo "Frontend IMAGE URI: ${{ needs.build-push-frontend-stg.outputs.latest_image_uri }}"
      - name: Render ECS task definition
        id: render-frontend-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: stg-front
          container-name: frontend
          image: ${{ needs.build-push-frontend-stg.outputs.latest_image_uri }}
      - name: Deploy Frontend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          cluster: stg-front
          service: stg-front-service
          task-definition: ${{ steps.render-frontend-task-def.outputs.task-definition }}
          wait-for-service-stability: true
      - name: "Debug: Built image URI (Frontend)"
        run: |
          echo "latest_image_uri: ${{ needs.build-push-frontend-stg.outputs.latest_image_uri }}" 