name: STG Terraform Infra Teardown
on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -upgrade -input=false

      - name: Terraform Destroy
        working-directory: infrastructure/terraform
        env:
          TF_VAR_db_password:   ${{ secrets.DB_PASSWORD }}
          TF_VAR_api_base_url:  ${{ secrets.API_BASE_URL }}
        run: terraform destroy -input=false -auto-approve

      - name: Cleanup ECS Task Execution IAM Role
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ROLE_NAME="${{ env.ENVIRONMENT || 'stg' }}-ecs-task-exec-role"
          aws iam detach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::${ACCOUNT_ID}:policy/TerraformSTGFullAccess || true
          aws iam detach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy || true
          aws iam detach-role-policy --role-name $ROLE_NAME --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly || true
          aws iam delete-role --role-name $ROLE_NAME || true 