name: STG Terraform Infra Setup

on:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infrastructure/terraform
        env:
          TF_VAR_db_password:   ${{ secrets.DB_PASSWORD }}
          TF_VAR_api_base_url:  ${{ secrets.API_BASE_URL }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: infrastructure/terraform
        env:
          TF_VAR_db_password:   ${{ secrets.DB_PASSWORD }}
          TF_VAR_api_base_url:  ${{ secrets.API_BASE_URL }}
        run: terraform apply -input=false -auto-approve tfplan 