name: PROD Terraform Infra Setup

on:
  workflow_dispatch: # 手動実行のみを想定

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: Production # 本番環境を指定 (GitHub Environments で承認設定を推奨)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }} # 本番用 AWS Credential を設定してください
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # 本番用 AWS Credential を設定してください
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0' # 必要に応じてバージョンを更新してください

      - name: Terraform Init
        working-directory: infrastructure/terraform
        run: terraform init -upgrade -input=false

      - name: Terraform Plan
        working-directory: infrastructure/terraform
        env:
          # ★★★ 本番用のシークレット名を指定してください ★★★
          TF_VAR_db_password:   ${{ secrets.DB_PASSWORD }}
          TF_VAR_api_base_url:  ${{ secrets.API_BASE_URL }}
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply (Requires manual approval)
        working-directory: infrastructure/terraform
        env:
          # ★★★ 本番用のシークレット名を指定してください ★★★
          TF_VAR_db_password:   ${{ secrets.DB_PASSWORD }}
          TF_VAR_api_base_url:  ${{ secrets.API_BASE_URL }}
        # apply コマンドから -auto-approve を削除
        # GitHub Environments の承認機能を利用して手動承認後に実行されることを想定
        run: terraform apply -input=false tfplan 