name: Lint

on:
  workflow_dispatch:
  # push: # 全てのブランチへのプッシュで実行

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('study-support-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
        working-directory: study-support-app
      - name: Run ESLint
        run: npm run lint -- --max-warnings=0
        working-directory: study-support-app

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r backend/requirements.txt
      - name: Run pylint
        run: |
          # Create a basic pylint configuration file
          echo "[MASTER]
          ignore=CVS
          persistent=yes
          load-plugins=

          [MESSAGES CONTROL]
          disable=C0111,R0903,C0103,R0201

          [REPORTS]
          output-format=text
          reports=yes
          evaluation=10.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10)
          " > backend/.pylintrc
          
          # Run pylint with the configuration file
          pylint backend --rcfile=backend/.pylintrc --fail-under=7.0 